// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonAll: typeof import('./src/components/common/common-all.vue')['default']
    CommonBottomplayer: typeof import('./src/components/common/common-bottomplayer.vue')['default']
    CommonLeftNav: typeof import('./src/components/common/common-leftNav.vue')['default']
    CommonMain: typeof import('./src/components/common/common-main.vue')['default']
    CommonTopNav: typeof import('./src/components/common/common-topNav.vue')['default']
    copy: typeof import('./src/components/common/common-all copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    Elemusic: typeof import('./src/components/elemusic/elemusic.vue')['default']
    ElemusicEnd: typeof import('./src/components/elemusic/elemusic-end.vue')['default']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeA: typeof import('./src/components/Home-a.vue')['default']
    MusicClub: typeof import('./src/components/body/music-club.vue')['default']
    MusicRecommend: typeof import('./src/components/body/music-recommend.vue')['default']
    Recommendation: typeof import('./src/components/body/recommendation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
