// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArtistDetail: typeof import('./src/components/body/artist-Detail.vue')['default']
    CommonBottomplayer: typeof import('./src/components/common/common-bottomplayer.vue')['default']
    CommonLeftNav: typeof import('./src/components/common/common-leftNav.vue')['default']
    CommonMain: typeof import('./src/components/common/common-main.vue')['default']
    CommonTopNav: typeof import('./src/components/common/common-topNav.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElemusicFinish: typeof import('./src/components/elemusic/elemusic-finish.vue')['default']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    MusicClub: typeof import('./src/components/body/music-club.vue')['default']
    MusicRecommend: typeof import('./src/components/body/music-recommend.vue')['default']
    MvBoFang: typeof import('./src/components/body/mvBoFang.vue')['default']
    PlaylistDetail: typeof import('./src/components/body/playlist-Detail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSuggest: typeof import('./src/components/small-panel/search-suggest.vue')['default']
    TiaoShi: typeof import('./src/components/body/tiao-shi.vue')['default']
  }
}
